name: timeblocks
description: "TimeBlocks - A visual time management app with calendar and notifications"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  device_calendar: ^4.3.2
  add_2_calendar: ^3.0.1
  fl_chart: ^0.66.0
  # Supabase dependencies
  supabase_flutter: ^2.5.6
  crypto: ^3.0.3
  # Deep link handling
  app_links: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # App icons
  assets:
    - assets/images/

  # App icon configuration for iOS
  generate: true
